openapi: 3.0.0

info:
  version: 0.0.1-alpha
  title: viaduct consus importing
  x-logo:
    url: "images/EDP_LOGO.png"

servers:
  - url: 'http://localhost:8080'
    description: Local development server
  - url: 'http://consus-importing.osapps.fokus.fraunhofer.de'
    description: Staging server at FOKUS

paths:
  /import:
    post:
      description: Start an importing session.
      summary: importing a repository
      operationId: importRepository
      requestBody:
        description: The job description and repository details.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/JobDescription'
        required: true
      responses:
        '202':
          description: Job acceped.
        '400':
          description: Validation error.

components:
  schemas:
    JobDescription:
      description: Information about the job and repository to import.
      type: object
      required:
        - id
        - repository
        - pipe
      properties:
        id:
          type: string
        repository:
          $ref: '#/components/schemas/Repository'
        pipe:
          $ref: '#/components/schemas/Pipe'
    Repository:
      description: A representation of a Repository.
      type: object
      required:
        - name
        - endpoint
      properties:
        _id:
          type: string
          readOnly: true
        name:
          type: string
        description:
          type: string
        endpoint:
          type: string
          format: uri
        type:
          type: string
          default: oai-pmh
          enum:
            - ckan
            - oai-pmh
            - sparql
        incremental:
          type: boolean
        region:
          type: array
          items:
            type: string
        language:
          type: string
        publisher:
          $ref: '#/components/schemas/Publisher'
    Publisher:
      description: Information about the publisher of a repository.
      type: object
      required:
        - name
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        homepage:
          type: string
          format: url
    Pipe:
      description: Information about the nect consumer.
      type: object
      required:
        - address
      properties:
        type:
          type: string
          enum: [ 'rest', 'eventbus' ]
          default: eventbus
        address:
          type: string