apiVersion: v1
kind: Service
metadata:
  name: {{ template "piveau-consus-importing-rdf.fullname" . }}
  labels:
    app: {{ template "piveau-consus-importing-rdf.fullname" . }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: default
      protocol: TCP
  selector:
    app: {{ template "piveau-consus-importing-rdf.fullname" . }}
